spring:
  datasource:
    url: jdbc:oracle:${DB_HOMOLOG_SERVER:thin:@oracle.fiap.com.br}:${DB_HOMOLOG_PORT:1521}:${DB_HOMOLOG_NAME:ORCL}
    username: "Rm97901"
    password: "070205"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true